apiVersion: v1
kind: Secret
metadata:
  name: sst-{{ include "google-tag-manager.fullname" . }}
  labels:
    {{- include "google-tag-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.serverSideTagging.secretEnvironment | nindent 2 }}
